Update TinyMCE installer
- Use production version instead of dev version, since we no longer
  need unminimized files for AMO
- Clean CSS to avoid console warnings

Works with TinyMCE 4.7.9

diff --git a/update-tinymce b/update-tinymce
--- a/update-tinymce
+++ b/update-tinymce
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -eu
+set -euo pipefail
 
 DIR="${1:-}/resource/tinymce"
 URL="${2:-}"
@@ -17,35 +17,68 @@ fi
 rm -rf "$DIR/tmp"
 mkdir "$DIR/tmp"
 cd "$DIR/tmp"
-wget $URL
-unzip -q *.zip
-rm -rf *.zip
+wget -O tinymce.zip $URL
+unzip -q tinymce.zip
+rm tinymce.zip
 cd tinymce/js/tinymce
 
 # Main file
-mv tinymce.js "$DIR/tinymce.js"
+mv tinymce.min.js "$DIR/tinymce.min.js"
 
 # Plugins
+rm -rf "$DIR/plugins"
 for p in autolink code contextmenu directionality link lists paste searchreplace textcolor; do
 	mkdir -p "$DIR/plugins/$p/"
-	mv plugins/$p/plugin.js "$DIR/plugins/$p/"
+	mv plugins/$p/plugin.min.js "$DIR/plugins/$p/"
 done
 
 # Patch link plugin
-rpl 'function openDetachedWindow(url) {' 'function openDetachedWindow(url) { /* Added by Zotero */ editor.execCommand("ZoteroLinkClick", false, url); } /*'  "$DIR/plugins/link/plugin.js"
-rpl 'function gotoLink(a) {' '*/function gotoLink(a) {'  "$DIR/plugins/link/plugin.js"
+if ! grep --quiet 'o=t.\$' "$DIR/plugins/link/plugin.min.js"; then
+	echo "Couldn't find 't' for editor in link plugin" >&2
+	exit 1
+fi
+if ! grep --quiet 'b(e.href)' "$DIR/plugins/link/plugin.min.js"; then
+	echo "Couldn't find 'b(e.href)' in link plugin" >&2
+	exit 1
+fi
+perl -pi -e 's/b\(e\.href\)/t.execCommand("ZoteroLinkClick", false, e.href)/' "$DIR/plugins/link/plugin.min.js"
 
-# Skin/theme
+# Skin
+rm -rf "$DIR/skins"
+mkdir -p "$DIR/skins/lightgray/fonts" "$DIR/skins/lightgray/img"
 for i in content.min.css skin.min.css; do
 	mv skins/lightgray/$i "$DIR/skins/lightgray/"
-done
-for i in anchor.gif loader.gif object.gif trans.gif; do
-	mv skins/lightgray/img/$i "$DIR/skins/lightgray/img/"
+	
+	file="$DIR/skins/lightgray/$i"
+	
+	# Remove unsupported CSS
+	perl -pi -e 's/-moz-box-shadow:[^;}]+;?//g' $file
+	perl -pi -e 's/filter:(alpha|progid)[^;}]+;?//g' $file
+	perl -pi -e 's/scrollbar-[a-z0-9]+-color:[^;}]+;?//g;' $file
+	perl -pi -e 's/speak:[^;}]+;?//g' $file
+	perl -pi -e 's/text-shadow:\dpx \dpx none;?//g' $file
+	perl -pi -e 's/(?<!-)user-modify:[^;}]+;?//g' $file
+	perl -pi -e 's/(?<!-)user-select:[^;}]+;?//g' $file
+	perl -pi -e 's/(?<!-)word-break:break-word;?//g' $file
+	perl -pi -e 's/zoom:[^;}]+;?//g' $file
+	# Strip CSS comments
+	perl -pi -e 's/\/\*[^*]+\*\///g' $file
+	# Strip declarations beginning with *, which would be dropped anyway
+	perl -pi -e 's/\*[a-z\-][^;}]+;?//g' $file
+	# Strip stray asterisks
+	perl -pi -e 's/;\*}/;}/g' $file
 done
 for i in tinymce-small.woff tinymce.woff; do
 	mv skins/lightgray/fonts/$i "$DIR/skins/lightgray/fonts/"
 done
-for i in theme.js; do
+for i in anchor.gif loader.gif object.gif trans.gif; do
+	mv skins/lightgray/img/$i "$DIR/skins/lightgray/img/"
+done
+
+# Theme
+rm -rf "$DIR/themes"
+mkdir -p "$DIR/themes/modern"
+for i in theme.min.js; do
 	cp themes/modern/$i "$DIR/themes/modern/"
 done
 
